### ISSUE TITLE
infer 字段类型，直到系统类型，请问如果避免？

### ISSUE THREAD

**Issue by myarth** [tangcent/easy-api#109]
ide plugin EasyApi 0.9.183.0.5 ，增强了接口返回类型推断；比如系统类型 Date ，会被当做 object 推断其属性，请问如何避免推断层次过深？
谢谢！

**Comment by tangcent** [comment]
- 当在<kbd>Preferences(Settings)</kbd> > <kbd>Other Settings</kbd> > <kbd>EasyApi</kbd>> <kbd>intelligent</kbd>启用 use recommmend config将自动引入如下配置
https://github.com/tangcent/easy-api/blob/cdf8c0daa4f276595d8f09ac05c45faf1ea23fb0/idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/config/RecommendConfigReader.kt#L74-L77

- 或者自行在配置中加入:
```
json.rule.convert[org.bson.types.ObjectId]=java.lang.String
json.rule.convert[java.util.Date]=java.lang.String
```

- 另外，如果有通用型的配置，可以发起一个PR，see  https://github.com/tangcent/easy-api/pull/106

**Comment by myarth** [comment]
谢谢。
另外，我发现配置中 java.util.Date 那一行少了 \n。
