### ISSUE TITLE
request body miss require and default column

### ISSUE THREAD

**Issue by anjia0532** [tangcent/easy-api#337]
**Is your feature request related to a problem? Please describe.**
Order.java
```java

@Data
public class Order {

    /**
     * orderId
     */
    @NotBlank(message = "order id must be not blank")
    @Schema(description = "order id", required = true, defaultValue = "xx", example = "demo")
    private String orderId;
}
```
.easy.api.config
```bash

#Support for javax.validation annotations
field.required=@"javax.validation.constraints.NotBlank
field.required=@javax.validation.constraints.NotNull
field.required=@javax.validation.constraints.NotEmpty
field.default.value=#default
field.required=@io.swagger.v3.oas.annotations.media.Schema#required
param.default.value=@io.swagger.v3.oas.annotations.media.Schema#defaultValue
param.ignore=@io.swagger.v3.oas.annotations.media.Schema#hidden
```

```java
    @PostMapping("/order-create")
    public Result<Void> orderCreate(@RequestBody Order order,
                                    @Schema(hidden = true) @RequestHeader("app-id") String appId) {
        return Result.ok();
    }
```

**output**

**RequestBody**

| name  |  type  |  desc  |
| ------------ | ------------ | ------------ |
| orderId | string| order id |

https://github.com/tangcent/easy-api/blob/ddd57a79fd3eaf3c0770d25146ac7061138894d5/idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/markdown/MarkdownFormatter.kt#L240-L264

**Describe the solution you'd like**

| name  |  type | required | default  |  desc  |
| ------------ | ------------| ------------| ------------ | ------------ |
| orderId | string|YES|xx| order id |

**Describe alternatives you've considered**

**Additional context**

**Comment by tangcent** [comment]
I am sick, and I will not be able to respond to this issue in about two weeks
