### ISSUE TITLE
[Feature] right click menus is so long

### ISSUE THREAD

**Issue by lizhuangs** [tangcent/easy-api#455]
**Describe the solution you'd like**
right click menus is so long
is there a way to make these one group like this
-->easy-api
&nbsp;&nbsp;-->export postman
&nbsp;&nbsp;-->export json
&nbsp;&nbsp;-->others

**Describe alternatives you've considered**
just make the right click menu looks concise and simple

**Comment by tangcent** [comment]
It is good. Maybe you can open a pull request for it. Otherwise I will pick it up this weekend.
