### ISSUE TITLE
[Feature]  php or thinkphp,thanks!

### ISSUE THREAD

**Issue by dly667** [tangcent/easy-api#480]
Is there any plan to support php or thinkphp?

**Comment by tangcent** [comment]
There are currently no plans to support non-Jvms.
I use python(flask) and nodeJs(express,koa) sometimes, and it seems difficult to parse the API information completely from the method signatures in dynamic languages. 
Often,  a lot of comments are required to describe API information.
From your perspective, how to parse api information from php source code?
