### ISSUE TITLE
使用easyapi 导出的接口，请求参数上并没有展示出对应的参数类型

### ISSUE THREAD

**Issue by linweifeng** [tangcent/easy-api#525]
如图：
![image](https://github.com/tangcent/easy-api/assets/14229312/c9dd15cf-1510-44a9-b619-e07fc2ef0549)

但是返回值是正常的：
![image](https://github.com/tangcent/easy-api/assets/14229312/41cfc66f-536b-437a-8cee-c066d5e90982)

类型

**Comment by tangcent** [comment]
yapi并没有为Query提供类型，你可以配置[param.doc](https://easyyapi.com/setting/rules/param_doc.html)来把类型信息放在备注里。

**Comment by linweifeng** [comment]
我还发现，当如果用post，把参数放在request body中导出，它是会展示对应的类型的，这里我理解应该是可以支持的。
