### ISSUE TITLE
The Settings page does not have the option to export the yapi configuration, it disappeared

### ISSUE THREAD

**Issue by pupansheng** [tangcent/easy-api#529]
The Settings page does not have the option to export the yapi configuration, it disappeared.

plug-version: 2.2.8.212.0
idea-version:2023.1.3

![image](https://github.com/tangcent/easy-api/assets/45847193/aaa23c2d-145d-45c5-b2b7-6bce72f7e2c6)

**Comment by tangcent** [comment]
Yes, easyapi does not include the feature of exporting to yapi.
You need to uninstall easyapi, then search for and download [EasyYapi](https://plugins.jetbrains.com/plugin/12458-easyyapi).

**Comment by pupansheng** [comment]
Thank you very much for your answer. I made a mistake about the plugin. I'm very sorry.
