### ISSUE TITLE
 be 

### ISSUE THREAD

**Issue by richwxd** [tangcent/easy-api#82]
**Describe the bug**
com.intellij.diagnostic.PluginException: action with the ID "com.itangcent.idea.easy_api.actions.PostmanExportAction" was already registered. Action being registered is ExportPostman (Export Postman); Registered action is Export Postman (Export Postman) Plugin: EasyApi [Plugin: com.itangcent.idea.plugin.easy-api]

**To Reproduce**
1. Open Idea
2. Open a spring-mybatis project

**Expected behavior**
No issue should be displayed.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Win10]

**Additional context**

**Comment by tangcent** [comment]
Hi,Please check your IDE for any other plugins which base on easy-api (like [easy-yapi](https://github.com/tangcent/easy-yapi)) had be installed.
In general, a plug-in that is re-developed based on easy-api should include all the features of easy-api(this is why action conflicts occur).
You should remove the easy-api from your IDE if you had installed any plugin re-developed based on easy-api.
